routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('login');
Route::get('logout', 'HomeController@logout')->name('logout');
Route::resource('score', 'ScoreController')->middleware('auth');;

Auth::routes();

app/Lop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lop extends Model
{
    protected $table = 'classes';
    protected $fillable = ['name'];


    public function student(){
    	return $this->belongsTo('App\Student', 'id');
    }

    public function scores(){
    	return $this->hasMany('App\Score', 'id');
    }
}

app/Score.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Score;
class Score extends Model
{
    protected $table = 'scores';
    protected $fillable = ['student_id', 'class_id','step', 'subject_id','score_mieng', 'score_15','score_60', 'score_last'];
    public $timestamps = false;

    public function student(){
    	return $this->belongsTo('App\Student', 'student_id');
    }

    public function lop(){
    	return $this->belongsTo('App\Lop', 'class_id');
    }

    public function subject(){
    	return $this->belongsTo('App\Subject', 'subject_id');
    }

    public static function getScoreAverage($id){
    	$score = self::findOrFail($id);
    	if($score){
    		if($score->score_mieng && $score->score_15 && $score->score_60 && $score->score_last){
    			return ($score->score_mieng + $score->score_15  +  $score->score_60  +  $score->score_last) / 4; 
    		}
    	}
    }

    public static function search($student_id, $class_id, $subject_id, $step){
        $query = new Score();
        if(isset($student_id) && !empty($student_id)){
            $query = $query->where('student_id', $student_id);
        }

        if(isset($class_id) && !empty($class_id)){
            $query = $query->where('class_id', $class_id);
        }

        if(isset($subject_id) && !empty($subject_id)){
            $query = $query->where('subject_id', $subject_id);
        }

        if(isset($step) && !empty($step)){
            $query = $query->where('step', $step);
        }
        return $query->paginate(10);
    }
}

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = 'students';
    protected $fillable = ['name', 'gender','class_id', 'birthday','address', 'nation','name_father', 'name_mother'];

    public function class(){
    	return $this->hasOne('App\Lop');
    }

    public function scores(){
    	return $this->hasMany('App\Score');
    }
}

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $table = 'subjects';
    protected $fillable = ['name'];
    
    public function scores(){
    	return $this->hasMany('App\Score');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if (Auth::check()) {
            return redirect()->route('score.index');
        }else{
            return redirect()->route('login');
        }
        // return view('home');
    }

    public function logout(){
        return Auth::logout();
    }
}

app/Http/Controllers/ScoreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Score;
use App\Student;
use App\Lop;
use App\Subject;
class ScoreController extends Controller
{
    protected $score;

    public function __construct(Score $score){
        $this->score = $score;
    }
    public function index(Request $request)
    {
        if($request->student_id || $request->class_id ||  $request->subject_id ||  $request->step  ){
            $items = $this->score->search($request->student_id, $request->class_id,$request->subject_id , $request->step);
        }else{
            $items = $this->score->orderBy('id','desc')->paginate(10);
        }
        $students = Student::all();
        $classes = Lop::all();
        $subjects = Subject::all();
        return view('score', compact('items','students', 'classes', 'subjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $students = Student::all();
        $classes = Lop::all();
        $subjects = Subject::all();
        return view('create', compact('students', 'classes', 'subjects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $score = new Score;
        $score->student_id = $request->student_id;
        $score->class_id = $request->class_id;
        $score->step = $request->step;
        $score->subject_id = $request->subject_id;
        $score->score_mieng = $request->score_mieng;
        $score->score_15 = $request->score_15;
        $score->score_60 = $request->score_60;
        $score->score_last = $request->score_last;
        $score->save();
        return redirect()->route('score.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $score = Score::findOrFail($id);
        return view('detail', compact('score'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $score = Score::findOrFail($id);
        $students = Student::all();
        $classes = Lop::all();
        $subjects = Subject::all();
        return view('edit', compact('students', 'classes', 'subjects', 'score'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $score = Score::findOrFail($id) ;
        $score->student_id = $request->student_id;
        $score->class_id = $request->class_id;
        $score->step = $request->step;
        $score->subject_id = $request->subject_id;
        $score->score_mieng = $request->score_mieng;
        $score->score_15 = $request->score_15;
        $score->score_60 = $request->score_60;
        $score->score_last = $request->score_last;
        $score->save();
        return redirect()->route('score.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Score::findOrFail($id)->delete();
        return redirect()->route('score.index');
    }
}

resources/views/create.blade.php
@extends('master')
@section('title', 'Thêm sinh viên')
@section('content')
	<form id="formCreateScore" action="{{ route('score.store') }}" method="POST">
		@csrf
		<div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<select name="student_id" class="form-control">
						<option value="">--- Chọn sinh viên ---</option>
				      	@foreach($students as $student)
				      		<option value="{{ $student->id }}">{{ $student->name }}</option>
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-6 mb-3">
					<select name="class_id" class="form-control">
						<option value="">--- Chọn lớp ---</option>
				      	@foreach($classes as $class)
				      		<option value="{{ $class->id }}">{{ $class->name }}</option>
				      	@endforeach 
				    </select>
				</div>
			</div>
	    </div>
	    <div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<select name="subject_id" class="form-control">
						<option value="">--- Chọn môn học ---</option>
				      	@foreach($subjects as $subject)
				      		<option value="{{ $subject->id }}">{{ $subject->name }}</option>
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-6 mb-3">
					<select name="step" class="form-control">
						<option value="">--- Chọn học kì ---</option>
				      	<option value="1">Học kì 1</option>
				      	<option value="2">Học kì 2</option>
				    </select>
				</div>
			</div>
	    </div>
	    <div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<input type="text" name="score_mieng" class="form-control" placeholder="Điểm miệng">
				</div>
				<div class="col-md-6 mb-3">
					<input type="text" name="score_15" class="form-control" placeholder="Điểm 15 phút">
				</div>
			</div>
	    </div>
	    <div class="form-group">
	    	<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<input type="text" name="score_60" class="form-control" placeholder="Điểm 1 tiết">
				</div>
				<div class="col-md-6 mb-3">
					<input type="text" name="score_last" class="form-control" placeholder="Điểm thi">
				</div>
			</div>
	    </div>
	    <div class="form-group">
	    	<div class="d-flex flex-row-reverse bd-highlight">
			  	<button class="btn btn-success" type="submit">Thêm</button>
			</div>
	    </div>
	</form>
	<script type="text/javascript">
		$( document ).ready(function() {
		    $("#formCreateScore").validate({
			    rules:{
			    	student_id:"required",
			    	class_id: "required",
			        step: "required",
			        subject_id:"required",
			        score_mieng: "number",
			        score_15: "number",
			        score_60: "number",
			        score_last: "number"
			    },
				messages: {
					student_id: "Vui lòng chọn sinh viên !",
					class_id: "Vui lòng chọn lớp học !",
					step: "Vui lòng chọn học kì !",
					subject_id: "Vui lòng chọn môn học !",
					score_mieng: "Điểm miệng phải là số" ,
					score_15: "Điểm 15 phút phải là số" ,
					score_60: "Điểm 1 tiết phải là số" ,
					score_last: "Điểm thi phải là số" ,
				}
			});
		});
	</script>
@endsection

resources/views/detail.blade.php
@extends('master')
@section('title', 'Chi tiết sinh viên')
@section('content')
	<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe2wwf2E2qriq_9LUjOjFyKx9MVC27Sv7Ia7vIuv9zJpVKdw0ROg" alt="" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        {{ $score->student->name }}
                    </h5>
                    <h6>
                        {{ $score->student->address }}
                    </h6>
                    @if($score->getScoreAverage($score->id))
                    	<p class="proile-rating">Điểm trung bình  : <span>{{ $score->getScoreAverage($score->id) }}</span></p>
                    @endif
                    
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Thông tin liên hệ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Điểm số </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Tên sinh viên</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->student->name }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Ngày sinh</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->student->birthday }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Giới tính</label>
                            </div>
                            <div class="col-md-6">
                                @if($score->student->gender == 1)
                                	<p>Nam</p>
                                @else
                                	<p>Nữ</p>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Địa chỉ</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->student->address }}</p>
                            </div>
                        </div>
                        
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Môn</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->subject->name }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Điểm miệng</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->score_mieng }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Điểm 15 phút</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->score_15 }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Điểm 1 tiết</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->score_60 }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Điểm thi</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ $score->score_last }}</p>
                            </div>
                        </div>
                        @if($score->getScoreAverage($score->id))
                        <div class="row">
                            <div class="col-md-12">
                                <label>Điểm trung bình</label>
                                <br/>
			                    <p class="proile-rating">Điểm trung bình  : <span>{{ $score->getScoreAverage($score->id) }}</span></p>
                            </div>
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<style type="text/css">
	.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
</style>
@endsection

resources/views/edit.blade.php
@extends('master')
@section('title', 'Cập nhật sinh viên')
@section('content')
	<form id="formCreateScore" action="{{ route('score.update', $score) }}" method="POST">
		@csrf
		@method('PUT')
		<div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<select name="student_id" class="form-control">
				      	@foreach($students as $student)
					      	@if($score->student_id == $student->id)
				      			<option selected value="{{ $score->student_id }}">{{ $student->name }}</option>
				      		@else
					      		<option value="{{ $student->id }}">{{ $student->name }}</option>
				      		@endif
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-6 mb-3">
					<select name="class_id" class="form-control">
				      	@foreach($classes as $class)
				      		@if($score->class_id == $class->id)
				      			<option selected value="{{ $score->student_id }}">{{ $class->name }}</option>
				      		@else
					      		<option value="{{ $class->id }}">{{ $class->name }}</option>
				      		@endif
				      	@endforeach 
				    </select>
				</div>
			</div>
	    </div>
	    <div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<select name="subject_id" class="form-control">
				      	@foreach($subjects as $subject)
				      		@if($score->subject_id == $subject->id)
				      			<option selected value="{{ $score->student_id }}">{{ $subject->name }}</option>
				      		@else
					      		<option value="{{ $subject->id }}">{{ $subject->name }}</option>
				      		@endif
				      		
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-6 mb-3">
					<select name="step" class="form-control">
				      	@if($score->step == 1)
							<option value="1" selected>Học kì 1</option>
							<option value="2">Học kì 2</option>
				    	@else
							<option value="2" selected>Học kì 2</option>
							<option value="1" >Học kì 1</option>
				    	@endif
				    </select>
				</div>
			</div>
	    </div>
	    <div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<input type="text" name="score_mieng" class="form-control" placeholder="Điểm miệng" value="{{ $score->score_mieng }}">
				</div>
				<div class="col-md-6 mb-3">
					<input type="text" name="score_15" class="form-control" placeholder="Điểm 15 phút" value="{{ $score->score_15 }}">
				</div>
			</div>
	    </div>
	    <div class="form-group">
	    	<div class="row  mb-3">
				<div class="col-md-6 mb-3">
					<input type="text" name="score_60" class="form-control" placeholder="Điểm 1 tiết" value="{{ $score->score_60 }}">
				</div>
				<div class="col-md-6 mb-3">
					<input type="text" name="score_last" class="form-control" placeholder="Điểm thi" value="{{ $score->score_last }}">
				</div>
			</div>
	    </div>
	    <div class="form-group">
	    	<div class="d-flex flex-row-reverse bd-highlight">
			  	<button class="btn btn-success" type="submit">Cập nhật</button>
			</div>
	    </div>
	</form>
	<script type="text/javascript">
		$( document ).ready(function() {
		    $("#formCreateScore").validate({
			    rules:{
			        score_mieng: "number",
			        score_15: "number",
			        score_60: "number",
			        score_last: "number"
			    },
				messages: {
					score_mieng: "Điểm miệng phải là số" ,
					score_15: "Điểm 15 phút phải là số" ,
					score_60: "Điểm 1 tiết phải là số" ,
					score_last: "Điểm thi phải là số" ,
				}
			});
		});
	</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>@yield('title')</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
<!-- jQuery library -->


<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style type="text/css">
	.error{
		color:red;
	}
</style>
<body>
    <div class="alert alert-success" role="alert">
      @yield('title')
    </div>
    <div class="container"> 
    	@yield('content')
    </div>
</body>
</html>

resources/views/score.blade.php
@extends('master')
@section('title', 'Danh sách sinh viên')
@section('content')
	<form method="GET">
		<div class="form-group" >
			<div class="row  mb-3">
				<div class="col-md-3 mb-3">
					<select name="student_id" class="form-control">
						<option value="">--- Chọn sinh viên ---</option>
				      	@foreach($students as $student)
				      		<option value="{{ $student->id }}">{{ $student->name }}</option>
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-3 mb-3">
					<select name="class_id" class="form-control">
						<option value="">--- Chọn lớp ---</option>
				      	@foreach($classes as $class)
				      		<option value="{{ $class->id }}">{{ $class->name }}</option>
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-3 mb-3">
					<select name="subject_id" class="form-control">
						<option value="">--- Chọn môn học ---</option>
				      	@foreach($subjects as $subject)
				      		<option value="{{ $subject->id }}">{{ $subject->name }}</option>
				      	@endforeach 
				    </select>
				</div>
				<div class="col-md-2 mb-3">
					<select name="step" class="form-control">
						<option value="">--- Chọn học kì ---</option>
				      	<option value="1">Học kì 1</option>
				      	<option value="2">Học kì 2</option>
				    </select>
				</div>
				<div class="form-group">
			    	<div class="d-flex flex-row-reverse bd-highlight">
					  	<button class="btn btn-success" type="submit">Tìm kiếm</button>
					</div>
			    </div>
			</div>

	    </div>
	    
	</form>
	<a href="{{ route('score.create') }}">Thêm sinh viên</a>
	<table class="table">
		<thead>
			<tr>
			  <th scope="col">ID</th>
			  <th scope="col">Sinh viên</th>
			  <th scope="col">Lớp</th>
			  <th scope="col">Học kỳ</th>
			  <th scope="col">Môn học</th>
			  <th scope="col">Điểm miệng</th>
			  <th scope="col">Điểm 15 phút</th>
			  <th scope="col">Điểm 1 tiết</th>
			  <th scope="col">Điểm thi</th>
			  <th scope="col">Điểm TB môn</th>
			  <th scope="col"></th>
			</tr>
		</thead>
	  	<tbody>

			@foreach($items as $key => $item)
				<tr>
					<th scope="row">{{ $key +1 }}</th>
					<td class="text-"><a href="{{ route('score.show', $item->id) }}">{{ $item->student->name }}</a></td>
					<td>{{ $item->lop->name }}</td>
					<td>{{ $item->step = 1 ? 'Học kì 1' : 'Học kì 2' }}</td>
					<td>{{ $item->subject->name }}</td>
					<td>{{ $item->score_mieng }}</td>
					<td>{{ $item->score_15 }}</td>
					<td>{{ $item->score_60 }}</td>
					<td>{{ $item->score_last }}</td>
					<td>{{ $item->getScoreAverage($item->id) }}</td>
					<td>
		                <div class="d-flex">
		                	<div>
		                		<a href="{{ route('score.edit', ['id' => $item->id]) }}">
									<button class="btn"><i class="fa fa-edit"></i></button>
								</a>
		                	</div>
		                	<div>
		                		<form action="{{ route('score.destroy', $item->id)}}" method="post">
				                  @csrf
				                  @method('DELETE')
								  	<button class="btn"><i class="fa fa-trash"></i></button>
				                </form>
		                	</div>
		                </div>
					</td>
				</tr>
			@endforeach
	  	</tbody>
	</table>
	<div class="d-flex flex-row-reverse bd-highlight">
	  	{{ $items->links() }}
	</div>
@endsection